apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-sample-app
  labels:
    app: green-sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: green-sample-app
  template:
    metadata:
      labels:
        app: green-sample-app
    spec:
      containers:
        - name: green-my-app
          image: asia-south1-docker.pkg.dev/s-0-009988/sample-app/my-app-green:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: green-sample-app-ilb
  annotations:
    cloud.google.com/backend-config: '{"default": "green-sample-app-backendconfig"}'
    cloud.google.com/neg: '{"exposed_ports": {"80":{"green-sample-app": "green-sample-app-80"}}}'  
spec:
  type: ClusterIP
  selector:
    app: green-sample-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
